### ISSUE TITLE
Is this project still alive ?

### ISSUE THREAD

**Issue by eikichi18** [lmcgartland/graphene-file-upload#40]
Hi,

I wrote just to say thanks for this package and to ask if this project was still alive because from 2018 i don't see any commit.

**Comment by davidroeca** [comment]
I’m still using it in my flask projects and haven’t had any major problems with it aside from the current error swallowing mentioned in #31 and #32 which is a hard problem to solve. I’d say that it’s currently in maintenance mode since there is no active maintainer. I’d be open to reviewing smaller bugfix pull requests, though. Big feature additions/functionality changes might take some additional effort, but if they solve some of the bigger problems, I’d be open to reviewing them in that case.

We also need better tests for Django, which I personally haven’t been motivated to write since I don’t use Django.

**Comment by eikichi18** [comment]
ok, thanks for quick reply. I wanted to know if project was alive because i have to use it in a project.
